sudo: required
services:
  - docker

before_install:
  - docker build -t dupinder/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dupinder/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  enviournment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-116142667750"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_key
  secret_access_key:
    secure: "$AWS_secrate_key"

